spring.application.name=QuoraReactiveApp
spring.data.mongodb.host=localhost
spring.data.mongodb.port=  27017
spring.data.mongodb.database=quora_db
spring.data.mongodb.auto-index-creation=true
kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=viewcount-consumer
spring.kafka.TOPIC_NAME=viewcount-topic 


spring.kafka.notify.TOPIC_NAME=likeNotify-topic 
spring.kafka.notify.consumer.group-id=likenotify-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true

spring.elasticsearch.uris=http://localhost:9200